version: '3'
services:
  build:
    image: node:12
    volumes:
      - ./$PROJECT_NAME:/usr/src/app/
    working_dir: /usr/src/app/
    command: bash -c "yarn upgrade && yarn global add gatsby-cli && gatsby build && gatsby serve -H 0.0.0.0"
    ports:
      - 9000:9000
