version: '3.3'

services:
  base:
    image: mygatsby_base
    # In rootless Docker, this causes issues
    # user: "${UID}:${GID}"
    volumes:
      - type: bind
        source: ./project/${PROJECT_NAME}
        target: /usr/src/app/
    working_dir: /usr/src/app/
    command: /bin/bash -c "yarn install"
