version: '3'
services:
  dev:
    image: mygatsby_base
    user: "${UID}:${GID}"
    volumes:
      - ./project/$PROJECT_NAME:/usr/src/app/
    working_dir: /usr/src/app/
    command: bash -c "gatsby develop -H 0.0.0.0"
    ports:
      - 8000:8000
