#!/bin/bash
read -p "Please input your email address: "
echo "EMAILADDY=$REPLY" >> .secret
read -p "Please input your name as you want it to appear in Git: "
echo "USERN=$REPLY" >> .secret
read -p "Please input the name for the directory of the new project: "
echo "PROJECT_NAME=$REPLY" >> .secret
read -p "Please input the source URL for your Gatsby project: "
echo "GATSBY_SOURCE=$REPLY" >> .secret
