version: '3'

services:
  base:
    build:
        context: .
        dockerfile: Dockerfile-myGatsby
    user: "${UID}:${GID}"
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    command: /bin/bash -c "gatsby new ${PROJECT_NAME} ${GATSBY_SOURCE}"
